In [ ]:
import pandas as pd
import numpy as np

# Importing Data

In [ ]:
df = pd.read_csv('/content/diabetes.csv')

In [ ]:
df.shape

(768, 9)

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
df.Glucose.unique()
df.Glucose.max()

199

In [ ]:
df[df['Glucose']==0]


Pregnancies  Glucose  ...  Age  Outcome
75             1        0  ...   22        0
182            1        0  ...   21        0
342            1        0  ...   22        0
349            5        0  ...   37        1
502            6        0  ...   41        1

[5 rows x 9 columns]

In [ ]:
df['Glucose'].replace(0,df['Glucose'].mean(), inplace = True)

In [ ]:
df[df['Glucose']==0]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [ ]:
df['SkinThickness'].unique()


array([35, 29,  0, 23, 32, 45, 19, 47, 38, 30, 41, 33, 26, 15, 36, 11, 31,
       37, 42, 25, 18, 24, 39, 27, 21, 34, 10, 60, 13, 20, 22, 28, 54, 40,
       51, 56, 14, 17, 50, 44, 12, 46, 16,  7, 52, 43, 48,  8, 49, 63, 99])

In [ ]:
df['BloodPressure'].replace(0,df['BloodPressure'].mean(), inplace = True)

In [ ]:
df['BloodPressure'].replace(0,df['BloodPressure'].mean(), inplace = True)
df['SkinThickness'].replace(0,df['SkinThickness'].mean(), inplace = True)
df['Insulin'].replace(0,df['Insulin'].mean(), inplace = True)
df['BMI'].replace(0,df['BMI'].mean(), inplace = True)
df['DiabetesPedigreeFunction'].replace(0,df['DiabetesPedigreeFunction'].mean(), inplace = True)


In [ ]:
df['SkinThickness'].unique()

array([35.        , 29.        , 20.53645833, 23.        , 32.        ,
       45.        , 19.        , 47.        , 38.        , 30.        ,
       41.        , 33.        , 26.        , 15.        , 36.        ,
       11.        , 31.        , 37.        , 42.        , 25.        ,
       18.        , 24.        , 39.        , 27.        , 21.        ,
       34.        , 10.        , 60.        , 13.        , 20.        ,
       22.        , 28.        , 54.        , 40.        , 51.        ,
       56.        , 14.        , 17.        , 50.        , 44.        ,
       12.        , 46.        , 16.        ,  7.        , 52.        ,
       43.        , 48.        ,  8.        , 49.        , 63.        ,
       99.        ])

In [ ]:
df.Outcome.unique()

array([1, 0])

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6    148.0           72.0  ...                     0.627   50        1
1            1     85.0           66.0  ...                     0.351   31        0
2            8    183.0           64.0  ...                     0.672   32        1
3            1     89.0           66.0  ...                     0.167   21        0
4            0    137.0           40.0  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
#test train split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Decision Tree, KNN, Naive Bayes, SVM

#**Decision Tree**

---






In [ ]:
 from sklearn.tree import DecisionTreeClassifier

 clf1 = DecisionTreeClassifier()
 clf1.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
X_test.shape

(254, 8)

In [ ]:
pred = clf1.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[115,  53],
       [ 26,  60]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.6889763779527559

#**K - Nearest Neighbors**

---



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()
neigh.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
pred = neigh.predict(X_test)

In [ ]:
confusion_matrix(y_test, pred)

array([[124,  44],
       [ 37,  49]])

In [ ]:
accuracy_score(y_test, pred)

0.6811023622047244

#**Naive Bayes**

---



In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
pred = gnb.fit(X_train, y_train).predict(X_test)

In [ ]:
confusion_matrix(y_test, pred)

array([[135,  33],
       [ 35,  51]])

In [ ]:
accuracy_score(y_test, pred)

0.7322834645669292

#**Support Vector Machines**

---



In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset\
pred = clf.predict(X_test)

In [ ]:
confusion_matrix(y_test, pred)

array([[140,  28],
       [ 37,  49]])

In [ ]:
accuracy_score(y_test, pred)

0.7440944881889764

In [ ]:
#Create a svm Classifier
clf = svm.SVC(kernel='poly') # Polynomial Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset\
pred = clf.predict(X_test)

confusion_matrix(y_test, pred)


array([[144,  24],
       [ 44,  42]])

In [ ]:
accuracy_score(y_test, pred)

0.7322834645669292

#**Standardization**

---



In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
clf1 = DecisionTreeClassifier()
clf1.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
confusion_matrix(y_test, pred)

array([[144,  24],
       [ 44,  42]])

In [ ]:
accuracy_score(y_test, pred)

0.7322834645669292

#**Principal Component Analysis**

---



In [ ]:
from sklearn.decomposition import PCA
 
pca = PCA(n_components = 2)
 
X_train1 = pca.fit_transform(X_train)
X_test1 = pca.transform(X_test)
 
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.2738123 , 0.19945418])

In [ ]:
clf1 = DecisionTreeClassifier()
clf1.fit(X_train1,y_train)

DecisionTreeClassifier()

In [ ]:
confusion_matrix(y_test, pred)

array([[144,  24],
       [ 44,  42]])

In [ ]:
accuracy_score(y_test, pred)

0.7322834645669292

In [ ]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

#**Logistic Regression**

---








In [ ]:
from sklearn.linear_model import LogisticRegression 
 
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train1, y_train)

LogisticRegression(random_state=0)

In [ ]:
pred = classifier.predict(X_test1)

In [ ]:
confusion_matrix(y_test, pred)

array([[136,  32],
       [ 47,  39]])

In [ ]:
accuracy_score(y_test, pred)

0.6889763779527559

#**Bagging**

---



In [ ]:
from sklearn.ensemble import BaggingClassifier
clf = BaggingClassifier(base_estimator=svm.SVC(), n_estimators=10, random_state=0).fit(X_train, y_train)

In [ ]:
pred = clf.predict(X_test)

In [ ]:
confusion_matrix(y_test, pred)

array([[139,  29],
       [ 44,  42]])

In [ ]:
accuracy_score(y_test, pred)

0.7125984251968503

#**Boosting**

---



In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0).fit(X_train, y_train)

In [ ]:
pred = clf.predict(X_test)
confusion_matrix(y_test, pred)

array([[134,  34],
       [ 31,  55]])

In [ ]:
accuracy_score(y_test, pred)

0.7440944881889764